### PR TITLE
updated references to use gopxl

### PR DESCRIPTION
**Pull request by duysqubix**

### CODE REVIEW

**Comment by duysqubix** [comment]
@dusk125 is this what you had in mind for a v1.0.0 release?

If so, I can merge this PR create a release and update the references to show a /v2

**Comment by dusk125** [comment]
Looks good to me. And yes, but I would change the repo name from "pixel2" to "pixel" as well after merging this. Then when you cut and share the release, it'll be the correct url.

**Comment by duysqubix** [comment]
Should we change it back to pixel2 afterwards?

Just wondering about the new logo and such.

**Comment by bhperry** [comment]
I like the idea of the repo being `gopxl/pixel`, so it lines up with the v2.0.0 `github.com/gopxl/pixel/v2` module name. Feels like a clean aesthetic than locking version info into the repo name.

**Comment by dusk125** [comment]
Agree with bhperry, cause if we ever decide to go to v3, we'd have to rename; better to rename once and now while we're still bootstrapping this project

**Comment by bhperry** [comment]
New logo is great though I don't see an issue with that

**Comment by dusk125** [comment]
Oh yeah also agreed!

**Comment by duysqubix** [comment]
Sounds good!

**Pull request merged**
